//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugManagement.Resx {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Parameter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parameter() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrugManagement.Resx.Parameter", typeof(Parameter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   食後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AfterMeals {
            get {
                return ResourceManager.GetString("AfterMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   毎 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlwaysMeals {
            get {
                return ResourceManager.GetString("AlwaysMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Appoint {
            get {
                return ResourceManager.GetString("Appoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BeforeMeals {
            get {
                return ResourceManager.GetString("BeforeMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BetweenMeals {
            get {
                return ResourceManager.GetString("BetweenMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   朝 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   夕 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _n_時間毎 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HourEach {
            get {
                return ResourceManager.GetString("HourEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   昼 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   就寝前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   頓服 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToBeTaken {
            get {
                return ResourceManager.GetString("ToBeTaken", resourceCulture);
            }
        }
    }
}
